media:
  input: public/uploads
  output: /uploads

content:
  - name: posts
    label: Blog Posts
    type: collection
    path: src/content/blog
    filename: '{fields.title}.md'
    view:
      fields: [title, date, draft]
      primary: title
      sort: [date]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: date
        label: Date
        type: date
        options:
          format: yyyy-MM-dd
        required: true
      - name: cover
        label: Cover image
        type: image
      - name: tags
        label: Tags
        type: string
        list: true
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: rich-text
